site_name: MJ'S KNTU Notes
theme:
  name: material
  language: fa
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: حالت تاریک
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: حالت روشن
  logo: Group 1w.png
  favicon: Group 1w.png
extra:
  generator: false
  copyright: "ساخته شده با مقادیر فراوان چای و حوصله بسیار توسط MJBakhshi "
  social:
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/mjb4khshi
extra_css:
  - extra.css
plugins:
  - search
  - ezlinks
  - callouts # برای تبدیل Calloutهای Obsidian
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - nl2br
