site_name: MJ'S KNTU Notes
theme:
  name: material
  language: fa
extra:
  generator: false
  footer: "ساخته شده با چای توسط MJBakhshi "
extra_css:
  - extra.css
plugins:
  - search
  - ezlinks
  - callouts # برای تبدیل Calloutهای Obsidian
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - nl2br
